### ISSUE TITLE
About HDFS_FDW

### ISSUE THREAD

**Issue by supriyakhosare** [EnterpriseDB/hdfs_fdw#1]
Hi....
i am triying HDFS_FDW on machine (ubuntu 14.04). but i am getting error on while issuing make command in cd libhive folder as follows... 
g++  -Wno-unused-variable -fPIC -Wall -g -I/opt/hadoop/thrift-0.9.2 -I/opt/hadoop/thrift-0.9.2/thrift -I/opt/hadoop/thrift-0.9.2/thrift/fb303 -Ithrift -Imetastore -Iodbc -Iodbc2 -Iql  -c -o thrift/hive_service_constants.o thrift/hive_service_constants.cpp
In file included from thrift/hive_service_constants.h:10:0,
                 from thrift/hive_service_constants.cpp:7:
thrift/hive_service_types.h:15:25: fatal error: fb303_types.h: No such file or directory
 #include "fb303_types.h"
                         ^
compilation terminated.
make: *** [thrift/hive_service_constants.o] Error 1

plz provide proper solution for the same....!!

**Comment by ibrarahmad** [comment]
You need to compile Thrift's fb303 library, I have updated the README file and checked-in the default path of fb303 and thrift.

cd thrift-0.9.2
cd contrib/fb303
./bootstrap.sh
./configure
make
make install

**Comment by ibrarahmad** [comment]
commit 80be879754b8243d83b83771a1a911050ae793a0
Author: Ibrar Ahmed <ibrar.ahmad@gmail.com>
Date:   Wed Feb 25 22:41:35 2015 +0500

**Comment by supriyakhosare** [comment]
Hello, 
Thanks for the responce, and its working but now i am getting an error while compiling  hdfs_fdw.
cd hdfs_fdw
make USE_PGXS=1 

gcc -O2 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I. -I/opt/PostgreSQL/9.3/include/postgresql/server -I/opt/PostgreSQL/9.3/include/postgresql/internal -D_GNU_SOURCE -I/opt/local/20140108/fc7f8f12-7861-11e3-aaff-000c29d23b02/include/libxml2  -I/usr/local/include/libxml2 -I/usr/local/include  -c -o hdfs_client.o hdfs_client.c
In file included from hdfs_client.c:20:0:
hdfs_fdw.h:112:2: error: unknown type name ‘HeapTuple’
  HeapTuple  *tuples;   /* array of currently-retrieved tuples */
  ^
hdfs_client.c: In function ‘hdfs_get_column_count’:
hdfs_client.c:40:2: warning: passing argument 2 of ‘DBGetColumnCount’ from incompatible pointer type [enabled by default]
  if (DBGetColumnCount(rs, &count, err_buf, sizeof(err_buf)) == HIVE_ERROR)
  ^
In file included from hdfs_client.c:18:0:
libhive/odbc/hiveclient.h:275:12: note: expected ‘size_t *’ but argument is of type ‘unsigned int *’
 HiveReturn DBGetColumnCount(HiveResultSet* resultset, size_t* col_count, char* err_buf,
            ^
hdfs_client.c: In function ‘hdfs_get_field_data_len’:
hdfs_client.c:52:2: warning: passing argument 3 of ‘DBGetFieldDataLen’ from incompatible pointer type [enabled by default]
  if (DBGetFieldDataLen(rs, col, &len, err_buf, sizeof(err_buf)) == HIVE_ERROR)
  ^
In file included from hdfs_client.c:18:0:
libhive/odbc/hiveclient.h:317:12: note: expected ‘size_t *’ but argument is of type ‘unsigned int *’
 HiveReturn DBGetFieldDataLen(HiveResultSet* resultset, size_t column_idx, size_t* col_len,
            ^
hdfs_client.c: In function ‘hdfs_get_field_as_cstring’:
hdfs_client.c:68:2: warning: passing argument 5 of ‘DBGetFieldAsCString’ from incompatible pointer type [enabled by default]
  if (DBGetFieldAsCString(rs, idx, value, len, &bs, &isnull, err_buf, sizeof(err_buf)) == HIVE_ERROR)
  ^
In file included from hdfs_client.c:18:0:
libhive/odbc/hiveclient.h:344:12: note: expected ‘size_t *’ but argument is of type ‘unsigned int *’
 HiveReturn DBGetFieldAsCString(HiveResultSet* resultset, size_t column_idx, char* buffer,
            ^
make: *** [hdfs_client.o] Error 1

**Comment by ibrarahmad** [comment]
It works fine on my machine, Ahsan can you please try on your machine.

On Sat, Feb 28, 2015 at 11:00 AM, supriyakhosare <notifications@github.com>
wrote:

> Hello,
> Thanks for the responce, and its working but now i am getting an error
> while compiling hdfs_fdw.
> cd hdfs_fdw
> make USE_PGXS=1
>
> gcc -O2 -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fpic -Wno-unused-variable
> -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2 -DHAVE_NETINET_IN_H
> -DHAVE_INTTYPES_H -I. -I. -I/opt/PostgreSQL/9.3/include/postgresql/server
> -I/opt/PostgreSQL/9.3/include/postgresql/internal -D_GNU_SOURCE
> -I/opt/local/20140108/fc7f8f12-7861-11e3-aaff-000c29d23b02/include/libxml2
> -I/usr/local/include/libxml2 -I/usr/local/include -c -o hdfs_client.o
> hdfs_client.c
> In file included from hdfs_client.c:20:0:
> hdfs_fdw.h:112:2: error: unknown type name ‘HeapTuple’
> HeapTuple *tuples; /* array of currently-retrieved tuples
>
>
>
>
>
>
>
> */ ^ hdfs_client.c: In function ‘hdfs_get_column_count’:
> hdfs_client.c:40:2: warning: passing argument 2 of ‘DBGetColumnCount’ from
> incompatible pointer type [enabled by default] if (DBGetColumnCount(rs,
> &count, err_buf, sizeof(err_buf)) == HIVE_ERROR) ^ In file included from
> hdfs_client.c:18:0: libhive/odbc/hiveclient.h:275:12: note: expected
> ‘size_t *’ but argument is of type ‘unsigned int *’ HiveReturn
> DBGetColumnCount(HiveResultSet* resultset, size_t* col_count, char*
> err_buf,
> ^
> hdfs_client.c: In function ‘hdfs_get_field_data_len’:
> hdfs_client.c:52:2: warning: passing argument 3 of ‘DBGetFieldDataLen’
> from incompatible pointer type [enabled by default]
> if (DBGetFieldDataLen(rs, col, &len, err_buf, sizeof(err_buf)) ==
> HIVE_ERROR)
> ^
> In file included from hdfs_client.c:18:0:
> libhive/odbc/hiveclient.h:317:12: note: expected ‘size_t
> *’ but argument is of type ‘unsigned int *’ HiveReturn
> DBGetFieldDataLen(HiveResultSet* resultset, size_t column_idx, size_t*
> col_len,
> ^
> hdfs_client.c: In function ‘hdfs_get_field_as_cstring’:
> hdfs_client.c:68:2: warning: passing argument 5 of ‘DBGetFieldAsCString’
> from incompatible pointer type [enabled by default]
> if (DBGetFieldAsCString(rs, idx, value, len, &bs, &isnull, err_buf,
> sizeof(err_buf)) == HIVE_ERROR)
> ^
> In file included from hdfs_client.c:18:0:
> libhive/odbc/hiveclient.h:344:12: note: expected ‘size_t
> *’ but argument is of type ‘unsigned int *’ HiveReturn
> DBGetFieldAsCString(HiveResultSet* resultset, size_t column_idx, char*
> buffer,
> ^
> make: *** [hdfs_client.o] Error 1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/hdfs_fdw/issues/1#issuecomment-76512757>.
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by ahsanhadi** [comment]
I noticed you close the ticket. Were you able to get it working?

**Comment by pavangadiya** [comment]
Hi All,
I am triying HDFS_FDW on the machine (centos 7.2). I am getting the similar error mentioned above while compiling hdfs_fdw.

Could you please help me to resolve this error.
Thank you!!


cd hdfs_fdw-master
make USE_PGXS=1

**gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_fdw.o hdfs_fdw.c
hdfs_fdw.c: In function ‘hdfs_fdw_handler’:
hdfs_fdw.c:96:30: warning: assignment from incompatible pointer type [enabled by default]
  routine->GetForeignPlan     = hdfsGetForeignPlan;
                              ^
hdfs_fdw.c: In function ‘hdfsGetForeignPaths’:
hdfs_fdw.c:223:12: warning: passing argument 8 of ‘create_foreignscan_path’ from incompatible pointer type [enabled by default]
            NIL);      /* no fdw_private list */
            ^
In file included from hdfs_fdw.c:31:0:
/usr/local/pgsql/include/server/optimizer/pathnode.h:82:21: note: expected ‘struct Path *’ but argument is of type ‘struct List *’
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
                     ^
hdfs_fdw.c:223:12: error: too few arguments to function ‘create_foreignscan_path’
            NIL);      /* no fdw_private list  @*/
            ^
In file included from hdfs_fdw.c:31:0:
/usr/local/pgsql/include/server/optimizer/pathnode.h:82:21: note: declared here
 extern ForeignPath *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel,
                     ^
hdfs_fdw.c: In function    @@@‘hdfsGetForeignPlan’:
hdfs_fdw.c:316:8: error: too few arguments to function ‘make_foreignscan’
        );
        ^
In file included from hdfs_fdw.c:33:0:
/usr/local/pgsql/include/server/optimizer/planmain.h:46:21: note: declared here
 extern ForeignScan *make_foreignscan(List *qptlist, List *qpqual,
                     ^
hdfs_fdw.c:317:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [hdfs_fdw.o] Error

**Comment by ibrarahmad** [comment]
What version of PostgreSQL are you using? Current version only works with
PostgreSQL 9.3/9.4

On Thu, Jan 28, 2016 at 7:26 PM, Pavan Gadiya <notifications@github.com>
wrote:

> Hi All,
> I am triying HDFS_FDW on the machine (centos 7.2). I am getting the
> similar error mentioned above while compiling hdfs_fdw.
>
> Could you please help me to resolve this error.
> Thank you!!
>
> cd hdfs_fdw-master
> make USE_PGXS=1
>
> *
>
>
>
>
>
>
> *gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -Wno-unused-variable -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2
> -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I. -I./
> -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal
> -D_GNU_SOURCE -c -o hdfs_fdw.o hdfs_fdw.c hdfs_fdw.c: In function
> ‘hdfs_fdw_handler’: hdfs_fdw.c:96:30: warning: assignment from incompatible
> pointer type [enabled by default] routine->GetForeignPlan =
> hdfsGetForeignPlan; ^ hdfs_fdw.c: In function ‘hdfsGetForeignPaths’:
> hdfs_fdw.c:223:12: warning: passing argument 8 of ‘create_foreignscan_path’
> from incompatible pointer type [enabled by default] NIL); /* no
> fdw_private list
>
>
>
>
>
>
> */ ^ In file included from hdfs_fdw.c:31:0:
> /usr/local/pgsql/include/server/optimizer/pathnode.h:82:21: note: expected
> ‘struct Path *’ but argument is of type ‘struct List *’ extern ForeignPath
> *create_foreignscan_path(PlannerInfo *root, RelOptInfo *rel, ^
> hdfs_fdw.c:223:12: error: too few arguments to function
> ‘create_foreignscan_path’ NIL); /* no fdw_private list @
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> */ ^ In file included from hdfs_fdw.c:31:0:
> /usr/local/pgsql/include/server/optimizer/pathnode.h:82:21: note: declared
> here extern ForeignPath *create_foreignscan_path(PlannerInfo *root,
> RelOptInfo *rel, ^ hdfs_fdw.c: In function @@@‘hdfsGetForeignPlan’:
> hdfs_fdw.c:316:8: error: too few arguments to function ‘make_foreignscan’
> ); ^ In file included from hdfs_fdw.c:33:0:
> /usr/local/pgsql/include/server/optimizer/planmain.h:46:21: note: declared
> here extern ForeignScan *make_foreignscan(List *qptlist, List *qpqual, ^
> hdfs_fdw.c:317:1: warning: control reaches end of non-void function
> [-Wreturn-type] } ^ make: *** [hdfs_fdw.o] Error
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/hdfs_fdw/issues/1#issuecomment-176206871>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by pavangadiya** [comment]
I am using PostgreSQL 9.5.0.
So Please suggest  What can I do to work with Postgres 9.5 & hdfs.fdw ?

**Comment by pavangadiya** [comment]
Hi Ibrar,
As you mentioned hdfs_fdw only works on postgres 9.3 & 9.4. 
So,I am using PostgreSQL 9.4.5 on centos  7.2 now.
Now, I am getting an error   while compiling hdfs_fdw.
Could you please help me to resolve this error. Thank you!

make USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_client.o hdfs_client.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_query.o hdfs_query.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_option.o hdfs_option.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_deparse.o hdfs_deparse.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_connection.o hdfs_connection.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_fdw.o hdfs_fdw.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -shared -o hdfs_fdw.so hdfs_client.o hdfs_query.o hdfs_option.o hdfs_deparse.o hdfs_connection.o hdfs_fdw.o -L/usr/local/pgsql/lib -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags  -L/usr/local/thrift/lib/ -Llibhive -lhive  -lfb303 -lstdc++ -lthrift
/usr/bin/ld: cannot find -lhive
collect2: error: ld returned 1 exit status

**Comment by pavangadiya** [comment]
Hey Ibrar & Ahsan,

Now, I tried a bit more but still getting this error while compiling hdfs_fdw.
Please help me out.

make USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -shared -o hdfs_fdw.so hdfs_client.o hdfs_query.o hdfs_option.o hdfs_deparse.o hdfs_connection.o hdfs_fdw.o -L/usr/local/pgsql/lib -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags  -L/usr/local/thrift/lib/ -Llibhive -lhive  -lfb303 -lstdc++ -lthrift
/usr/bin/ld: /usr/local/lib/libfb303.a(FacebookService.o): relocation R_X86_64_32S against `_ZNSs4_Rep20_S_empty_rep_storageE' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfb303.a: could not read symbols: Bad value

**Comment by ibrarahmad** [comment]
I have pushed the PostgreSQL 9.5 changes. Now it should work with Version
9.5.

On Mon, Feb 1, 2016 at 7:35 PM, Pavan Gadiya <notifications@github.com>
wrote:

> Hi Ibrar,
> As you mentioned hdfs_fdw only works on postgres 9.3 & 9.4.
> So,I am using PostgreSQL 9.4.5 on centos 7.2 now.
> Now, I am getting an error while compiling hdfs_fdw.
> Could you please help me to resolve this error. Thank you!
>
> make USE_PGXS=1
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -Wno-unused-variable -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2
> -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I. -I./
> -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal
> -D_GNU_SOURCE -c -o hdfs_client.o hdfs_client.c
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -Wno-unused-variable -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2
> -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I. -I./
> -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal
> -D_GNU_SOURCE -c -o hdfs_query.o hdfs_query.c
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -Wno-unused-variable -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2
> -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I. -I./
> -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal
> -D_GNU_SOURCE -c -o hdfs_option.o hdfs_option.c
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -Wno-unused-variable -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2
> -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I. -I./
> -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal
> -D_GNU_SOURCE -c -o hdfs_deparse.o hdfs_deparse.c
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -Wno-unused-variable -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2
> -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I. -I./
> -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal
> -D_GNU_SOURCE -c -o hdfs_connection.o hdfs_connection.c
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -Wno-unused-variable -Ilibhive -Ilibhive/odbc -Ilibhive/odbc2
> -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H -I. -I./
> -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal
> -D_GNU_SOURCE -c -o hdfs_fdw.o hdfs_fdw.c
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -shared -o hdfs_fdw.so hdfs_client.o hdfs_query.o hdfs_option.o
> hdfs_deparse.o hdfs_connection.o hdfs_fdw.o -L/usr/local/pgsql/lib
> -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags
> -L/usr/local/thrift/lib/ -Llibhive -lhive -lfb303 -lstdc++ -lthrift
> /usr/bin/ld: cannot find -lhive
> collect2: error: ld returned 1 exit status
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/hdfs_fdw/issues/1#issuecomment-177996539>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by ibrarahmad** [comment]
On Mon, Feb 1, 2016 at 8:06 PM, Pavan Gadiya <notifications@github.com>
wrote:

> Hey Ibrar & Ahsan,
>
> Now, I tried a bit more but still getting this error while compiling
> hdfs_fdw.
> Please help me out.
>
> make USE_PGXS=1
> gcc -Wall -Wmissing-prototypes -Wpointer-arith
> -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute
> -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard
> -O2 -fpic -shared -o hdfs_fdw.so hdfs_client.o hdfs_query.o hdfs_option.o
> hdfs_deparse.o hdfs_connection.o hdfs_fdw.o -L/usr/local/pgsql/lib
> -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags
> -L/usr/local/thrift/lib/ -Llibhive -lhive -lfb303 -lstdc++ -lthrift
> /usr/bin/ld: /usr/local/lib/libfb303.a(FacebookService.o): relocation
> R_X86_64_32S against `_ZNSs4_Rep20_S_empty_rep_storageE' can not be used
> when making a shared object; recompile with -fPIC
> /usr/local/lib/libfb303.a: could not read symbols: Bad value
>


Please try

- make clean
 - make



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnterpriseDB/hdfs_fdw/issues/1#issuecomment-178006782>
> .
>



-- 
Ibrar Ahmed
EnterpriseDB   http://www.enterprisedb.com

**Comment by pavangadiya** [comment]
Thanks for the reply Ibrar.

I tried with make clean & make but still getting the error.

Please check the issue. Thank You!

[hdfs_fdw-master]# make clean
rm -f hdfs_fdw.so   libhdfs_fdw.a  libhdfs_fdw.pc
rm -f hdfs_client.o hdfs_query.o hdfs_option.o hdfs_deparse.o hdfs_connection.o hdfs_fdw.o
rm -rf results/ regression.diffs regression.out tmp_check/ log/

[ hdfs_fdw-master]# make USE_PGXS=1
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_client.o hdfs_client.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_query.o hdfs_query.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_option.o hdfs_option.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_deparse.o hdfs_deparse.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_connection.o hdfs_connection.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -Wno-unused-variable -Ilibhive  -Ilibhive/odbc  -Ilibhive/odbc2 -DHAVE_NETINET_IN_H -DHAVE_INTTYPES_H  -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal -D_GNU_SOURCE   -c -o hdfs_fdw.o hdfs_fdw.c
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fpic -shared -o hdfs_fdw.so hdfs_client.o hdfs_query.o hdfs_option.o hdfs_deparse.o hdfs_connection.o hdfs_fdw.o -L/usr/local/pgsql/lib -Wl,--as-needed -Wl,-rpath,'/usr/local/pgsql/lib',--enable-new-dtags  -L/usr/local/thrift/lib/ -Llibhive -lhive  -lfb303 -lstdc++ -lthrift
/usr/bin/ld: /usr/local/lib/libfb303.a(FacebookService.o): relocation R_X86_64_32S against `_ZNSs4_Rep20_S_empty_rep_storageE' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfb303.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [hdfs_fdw.so] Error 1
